#ifndef CONFIG_H
#define CONFIG_H

//Header to store some configuration value
#define BOARD_START_POINT -300
#define SINGLE_BOARD_SIZE 200
#define SQUARE_SIZE SINGLE_BOARD_SIZE/3
#define MINI_SQUARE_SIZE SQUARE_SIZE/3
#define OFFSET_BETWEEN_BOARDS 10
#define THICK_PEN_THICKNESS 5
#define NORMAL_PEN_THICKNESS 3 
#define THIN_PEN_THICKNESS 1

#define EMPTY_VALUE 0


#endif //CONFIG_H